# 🤖 AI-OPTIMIZED CONFIGURATION
# Generated by Emergency AI Optimizer
# Timestamp: 2025-10-11 12:01:53
#
# 🚨 CRISIS CONTEXT:
# - Baseline strategy failed: 5% win rate today
# - Lost R-1,106 in 20 trades
# - AI found these optimal parameters:

# ===============================================
# CRITICAL SETTINGS - DO NOT CHANGE MANUALLY
# ===============================================

# ===============================================
# PHASE 1 CONFIGURATION - MONITOR ONLY MODE
# ===============================================
PAPER_TRADING = True        # True = use paper trading execution
MONITOR_ONLY_MODE = False     # False = enable execution paths
AMBIGUOUS_AI = False  # deprecated typo guard, do not use
AMBITIOUS_AI = False  # Set True to enable ambitious OzzyAIAgent parallel analysis
OPTIMIZED_BYBIT_CLIENT = True  # Use caching/batching/rate-limited Bybit client

# Phase 1 optimized parameters (lower thresholds for more signals)
RSI_OVERSOLD = 40              # Easier to trigger
RSI_OVERBOUGHT = 60            # Easier to trigger  
EMA_SHORT = 13                 # Keep AI optimized value
EMA_LONG = 23                  # Keep AI optimized value
MIN_CONFIDENCE = 30.0          # Lower for more signals

# 🕒 AI-OPTIMIZED TRADING HOURS (avoid low-liquidity periods)
TRADING_HOURS = {
    'enabled': False,  # 24/7 trading
    'start': 0,
    'end': 24
}

# ===============================================
# PERFORMANCE PROJECTIONS
# ===============================================
# Based on historical backtesting:
# 📊 Projected Win Rate: 67.5%
# 💰 Projected Profit Factor: 3.19
# 📈 Avg Trade: R38.68

# ===============================================
# UNCHANGED SETTINGS (kept from baseline)
# ===============================================

# API Configuration (Bybit) - Phase 1 Live Data
BYBIT_API_KEY = "fpToarfmHL7DvE17UQ"        # Live API key
BYBIT_API_SECRET = "fUv6letFOd2jSPxmFnmuxmkPx83nJ9DMw53p"   # Live API secret  
BYBIT_TESTNET = False  # False = live exchange for Phase 1

# Legacy/other APIs (kept for compatibility in other scripts)
BINANCE_API_KEY = "your_api_key_here"
BINANCE_API_SECRET = "your_secret_here"

# Symbols to trade
SYMBOLS = ["BTCUSDT", "ETHUSDT"]
# Alias used by some modules
TRADING_SYMBOLS = SYMBOLS

# Position management
LEVERAGE = 1.0
POSITION_SIZE_PERCENTAGE = 2.0
STOP_LOSS_PERCENTAGE = 3.0
TAKE_PROFIT_PERCENTAGE = 6.0
# Aliases used by some modules
STOP_LOSS_PERCENT = STOP_LOSS_PERCENTAGE
TAKE_PROFIT_PERCENT = TAKE_PROFIT_PERCENTAGE

# Technical analysis
BB_PERIOD = 20
BB_STD = 2
VOLUME_THRESHOLD = 1.5

# Risk management
MAX_OPEN_POSITIONS = 3
MAX_POSITIONS = MAX_OPEN_POSITIONS  # Keep runtime caps aligned
DAILY_LOSS_LIMIT = 1000.0  # Allow more daily loss before blocking
MAX_DAILY_LOSS = 5  # % of starting capital allowed before circuit breaker
WEEKLY_LOSS_LIMIT = 2000.0
RISK_PER_TRADE = 0.02  # 2% default risk per trade
SHORT_MARGIN = 0.10    # 10% margin requirement for simulated shorts

# Balance settings
INITIAL_BALANCE = 10000.0
STARTING_CAPITAL = INITIAL_BALANCE  # alias for consumers
BALANCE_CHECK_INTERVAL = 3600

# Logging
LOG_LEVEL = "INFO"
LOG_FILE = "bot.log"

# Scheduler/loop
CHECK_INTERVAL_MINUTES = 1  # how often to poll for signals
CLOSE_POSITIONS_EOD = False

# Paper trading behavior
PAPER_SLIPPAGE = 0.0002  # 2 bps slippage on simulated executions

# ============================================
# TIME FILTER (A/B) SETTINGS
# ============================================
# When False, the bot will not avoid any hours; trades can execute 24/7.
TIME_FILTER_ENABLED = False  # Ensure time filter is off
# Default avoid windows (UTC) used only if TIME_FILTER_ENABLED=True
TIME_FILTER_AVOID_WINDOWS = [(22, 2)]

# ============================================
# PHASE 2 CONFIGURATION TOGGLES
# ============================================
PHASE_2_MODE = True
USE_AI_OPTIMIZER = True
MIN_AI_CONFIDENCE_APPROVE = 35.0  # Lowered to 35% to allow current AI confidence levels
MIN_AI_CONFIDENCE_IMPROVE = 30.0   # Lowered to 30% to capture even marginal setups
MIN_OPPORTUNITY_SCORE_IMPROVE = 4.0  # Lowered to 4.0 (40% confidence equivalent)
MIN_OPPORTUNITY_SCORE_CHALLENGE = 6.0
RISK_PER_TRADE = 0.02  # 2% default risk per trade
RISK_PER_TRADE_PCT = 0.02  # 2% risk per trade
EXECUTE_ON_APPROVE = True
EXECUTE_ON_IMPROVE = True
EXECUTE_ON_CHALLENGE = True
EXECUTE_ON_COUNTER = False

# Phase 2 paper sizing controls
# If enabled, Phase 2 uses a fixed percentage of capital per trade (position value),
# otherwise it falls back to Adaptive Position Sizing (if enabled) or risk-based sizing.
PHASE_2_USE_FIXED_POSITION = False
PHASE_2_FIXED_POSITION_PCT = 0.30  # legacy default; ignored when PHASE_2_USE_FIXED_POSITION=False

# Portfolio exposure cap for Phase 2
PORTFOLIO_EXPOSURE_CAP_PCT = 0.50  # 50% of capital total notional exposure cap
MAX_POSITION_PCT = 0.20  # 20% per position cap
RISK_PER_TRADE_PCT = 0.02  # 2% risk per trade

# Legacy hour settings (overridden by TRADING_HOURS)
TRADING_START_HOUR = TRADING_HOURS['start'] if TRADING_HOURS['enabled'] else 0
TRADING_END_HOUR = TRADING_HOURS['end'] if TRADING_HOURS['enabled'] else 24

def print_config():
    """Print configuration summary"""
    print("\n🤖 AI-OPTIMIZED OZZY CONFIGURATION")
    print("="*50)
    print(f"RSI: {RSI_OVERSOLD}-{RSI_OVERBOUGHT}")
    print(f"EMA: {EMA_SHORT}/{EMA_LONG}")
    print(f"Min Confidence: {MIN_CONFIDENCE}%")
    if TRADING_HOURS['enabled']:
        print(f"Trading Hours: {TRADING_HOURS['start']:02d}:00-{TRADING_HOURS['end']:02d}:00 SAST")
    else:
        print("Trading Hours: 24/7")
    print(f"Mode: {'PAPER TRADING' if PAPER_TRADING else 'LIVE TRADING'}")
    print("="*50)

if __name__ == "__main__":
    print_config()

# ================================================================
# DYNAMIC ADAPTIVE POSITION SIZING (DAPS)
# Feature-flagged to avoid breaking existing flows.
# ================================================================
# Enable adaptive sizing system
ADAPTIVE_SIZING_ENABLED = True

# Starting capital used by adaptive manager is the global STARTING_CAPITAL defined above

# Base percentages per tier
BASE_TIER_1_PCT = 0.03
BASE_TIER_2_PCT = 0.015
BASE_TIER_3_PCT = 0.0075

# Safety rails
ABSOLUTE_MIN_POSITION = 50
# For Phase 2 paper trading experiments, allow larger position caps and deployed percentage
ABSOLUTE_MAX_POSITION = 3000   # up to R3,000 on R10,000 capital (30%)
ABSOLUTE_MAX_RISK_PCT = 0.30   # cap risk per trade at 30% (paper only)
ABSOLUTE_MAX_DEPLOYED_PCT = 0.30  # do not deploy more than 30% per trade
ABSOLUTE_DAILY_LOSS_LIMIT = 500

# Performance/confidence settings
PERFORMANCE_LOOKBACK_TRADES = 20
ENABLE_CONFIDENCE_MULTIPLIER = True
ENABLE_CAPITAL_GROWTH_SCALING = True

# Reporting controls
LOG_POSITION_CALCULATIONS = True
ALERT_ON_SAFETY_RAIL_HIT = True

# ================================================================
# MULTI-ASSET DIVERSIFIED PORTFOLIO (feature-flagged)
# Keeps existing behavior unless explicitly enabled.
# ================================================================
MULTI_ASSET_ENABLED = False  # Only trade BTC/ETH for now

# Suggested diversified set (Gold + Top 3 Forex + Major/Alt Crypto)
MULTI_ASSET_SYMBOLS = [
    'XAUUSDT',
    'EURUSD', 'GBPUSD', 'USDJPY',
    'BTCUSDT', 'ETHUSDT',
    # ALTCOINS TEMPORARILY DISABLED (2025-10-11)
    # 'SOLUSDT', 'BNBUSDT',
]

# Capital allocation per symbol (fractions of STARTING_CAPITAL)
ASSET_ALLOCATION = {
    # ALTCOINS TEMPORARILY DISABLED (2025-10-11)
    # Reason: Lost ~R-1,072 on 32 altcoin trades; focusing on smoother assets
    'XAUUSDT': 0.28,   # +3%
    'EURUSD': 0.17,    # +2%
    'GBPUSD': 0.12,    # +2%
    'USDJPY': 0.12,    # +2%
    'BTCUSDT': 0.16,   # +1%
    'ETHUSDT': 0.15,   # unchanged
    # 'SOLUSDT': 0.00,
    # 'BNBUSDT': 0.00,
}

# Asset-specific parameters (TP/SL in percent, technicals, thresholds)
ASSET_PARAMETERS = {
    'XAUUSDT': { 'take_profit_pct': 0.015, 'stop_loss_pct': 0.010, 'rsi_oversold': 35, 'rsi_overbought': 65, 'ema_short': 13, 'ema_long': 23, 'min_confidence': 40, 'max_leverage': 1 },
    'EURUSD':  { 'take_profit_pct': 0.008, 'stop_loss_pct': 0.005, 'rsi_oversold': 30, 'rsi_overbought': 70, 'ema_short': 9,  'ema_long': 21, 'min_confidence': 38, 'max_leverage': 1, 'pip_value': 0.0001 },
    'GBPUSD':  { 'take_profit_pct': 0.012, 'stop_loss_pct': 0.008, 'rsi_oversold': 28, 'rsi_overbought': 72, 'ema_short': 9,  'ema_long': 21, 'min_confidence': 42, 'max_leverage': 1, 'pip_value': 0.0001 },
    'USDJPY':  { 'take_profit_pct': 0.010, 'stop_loss_pct': 0.007, 'rsi_oversold': 32, 'rsi_overbought': 68, 'ema_short': 13, 'ema_long': 26, 'min_confidence': 40, 'max_leverage': 1, 'pip_value': 0.01 },
    'BTCUSDT': { 'take_profit_pct': 0.035, 'stop_loss_pct': 0.025, 'rsi_oversold': 39, 'rsi_overbought': 67, 'ema_short': 13, 'ema_long': 23, 'min_confidence': 41, 'max_leverage': 1 },
    'ETHUSDT': { 'take_profit_pct': 0.040, 'stop_loss_pct': 0.028, 'rsi_oversold': 39, 'rsi_overbought': 67, 'ema_short': 13, 'ema_long': 23, 'min_confidence': 41, 'max_leverage': 1 },
    'SOLUSDT': { 'take_profit_pct': 0.050, 'stop_loss_pct': 0.035, 'rsi_oversold': 35, 'rsi_overbought': 70, 'ema_short': 9,  'ema_long': 21, 'min_confidence': 45, 'max_leverage': 1 },
    'BNBUSDT': { 'take_profit_pct': 0.050, 'stop_loss_pct': 0.035, 'rsi_oversold': 35, 'rsi_overbought': 70, 'ema_short': 9,  'ema_long': 21, 'min_confidence': 45, 'max_leverage': 1 },
}

# Trading hours guidance per symbol (UTC hours; inclusive)
ASSET_TRADING_HOURS = {
    'XAUUSDT': { 'enabled': True, 'sessions': [ {'start': 13, 'end': 21} ] },  # approx London/NY overlap in UTC
    'EURUSD':  { 'enabled': True, 'sessions': [ {'start': 7,  'end': 16}, {'start': 12, 'end': 17} ] },
    'GBPUSD':  { 'enabled': True, 'sessions': [ {'start': 7,  'end': 16} ] },
    'USDJPY':  { 'enabled': True, 'sessions': [ {'start': 0,  'end': 8 } ] },
    'BTCUSDT': { 'enabled': True, 'sessions': [ {'start': 0,  'end': 23} ] },
    'ETHUSDT': { 'enabled': True, 'sessions': [ {'start': 0,  'end': 23} ] },
    'SOLUSDT': { 'enabled': True, 'sessions': [ {'start': 8,  'end': 20} ] },
    'BNBUSDT': { 'enabled': True, 'sessions': [ {'start': 8,  'end': 20} ] },
}

# Tiered position sizing on allocated capital (preview values)
TIER_1_POSITION_PCT = 0.04
TIER_2_POSITION_PCT = 0.02
TIER_3_POSITION_PCT = 0.01

# If multi-asset mode is enabled, override TRADING_SYMBOLS to diversified set
try:
    if MULTI_ASSET_ENABLED:
        TRADING_SYMBOLS = MULTI_ASSET_SYMBOLS
except NameError:
    # Safe guard if variables not yet defined in some contexts
    pass
