# 🤖 AI-OPTIMIZED CONFIGURATION
# Generated by Emergency AI Optimizer
# Timestamp: 2025-10-11 12:01:53
#
# 🚨 CRISIS CONTEXT:
# - Baseline strategy failed: 5% win rate today
# - Lost R-1,106 in 20 trades
# - AI found these optimal parameters:

# ===============================================
# CRITICAL SETTINGS - DO NOT CHANGE MANUALLY
# ===============================================

PAPER_TRADING = True         # True = simulate trades, False = real trades

# 🎯 AI-OPTIMIZED PARAMETERS
RSI_OVERSOLD = 39              # AI Optimized: 39 (was 30)
RSI_OVERBOUGHT = 67            # AI Optimized: 67 (was 70)
EMA_SHORT = 13                   # AI Optimized: 13 (was 12)
EMA_LONG = 23                    # AI Optimized: 23 (was 21)
MIN_CONFIDENCE = 41.1          # AI Optimized: 41.1% (was 25%)

# 🕒 AI-OPTIMIZED TRADING HOURS (avoid low-liquidity periods)
TRADING_HOURS = {
    'enabled': True,
    'start': 10,                     # AI Optimized: 10:00 SAST
    'end': 21,                       # AI Optimized: 21:00 SAST
    'timezone': 'Africa/Johannesburg'
}

# ===============================================
# PERFORMANCE PROJECTIONS
# ===============================================
# Based on historical backtesting:
# 📊 Projected Win Rate: 67.5%
# 💰 Projected Profit Factor: 3.19
# 📈 Avg Trade: R38.68

# ===============================================
# UNCHANGED SETTINGS (kept from baseline)
# ===============================================

# API Configuration
BINANCE_API_KEY = "your_api_key_here"
BINANCE_API_SECRET = "your_secret_here"

# Symbols to trade
SYMBOLS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "SOLUSDT"]

# Position management
LEVERAGE = 1.0
POSITION_SIZE_PERCENTAGE = 2.0
STOP_LOSS_PERCENTAGE = 3.0
TAKE_PROFIT_PERCENTAGE = 6.0

# Technical analysis
BB_PERIOD = 20
BB_STD = 2
VOLUME_THRESHOLD = 1.5

# Risk management
MAX_OPEN_POSITIONS = 3
DAILY_LOSS_LIMIT = 500.0
WEEKLY_LOSS_LIMIT = 2000.0

# Balance settings
INITIAL_BALANCE = 10000.0
BALANCE_CHECK_INTERVAL = 3600

# Logging
LOG_LEVEL = "INFO"
LOG_FILE = "bot.log"

# Legacy hour settings (overridden by TRADING_HOURS)
TRADING_START_HOUR = TRADING_HOURS['start'] if TRADING_HOURS['enabled'] else 0
TRADING_END_HOUR = TRADING_HOURS['end'] if TRADING_HOURS['enabled'] else 24

def print_config():
    """Print configuration summary"""
    print("\n🤖 AI-OPTIMIZED OZZY CONFIGURATION")
    print("="*50)
    print(f"RSI: {RSI_OVERSOLD}-{RSI_OVERBOUGHT}")
    print(f"EMA: {EMA_SHORT}/{EMA_LONG}")
    print(f"Min Confidence: {MIN_CONFIDENCE}%")
    if TRADING_HOURS['enabled']:
        print(f"Trading Hours: {TRADING_HOURS['start']:02d}:00-{TRADING_HOURS['end']:02d}:00 SAST")
    else:
        print("Trading Hours: 24/7")
    print(f"Mode: {'PAPER TRADING' if PAPER_TRADING else 'LIVE TRADING'}")
    print("="*50)

if __name__ == "__main__":
    print_config()
